[project]
name = "trajectoryvisual-1"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "rtree>=1.4.0",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1",
]
